### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by stephenfuqua** [FlightNode/FlightNode.Api#23]
As a project coordinator, I want to maintain a list of frequently asked questions and answers, so that a general audience can learn more about the project.
# Notes
- Basic HTML editing
- Each entry would be in the form of a Question and an Answer
- Manage n-number of entries
# Sub-tasks
- [ ] admin page listing Q & A entries
- [ ] admin page / popup for editing Q & A entries (direct HTML input)
- [ ] admin page / popup for editing Q & A entries (use an editor, e.g. CKEdit or Kendo's editor)
- [ ] ensure not able to inject malicious HTML / JS / CSS
- [ ] public page for displaying Q & A entries
